### ISSUE TITLE
Client not loading configurations

### ISSUE THREAD

**Issue by KuroNoSeiHai** [ProjectEssentials/ProjectEssentials-Core#10]
1.15.2 when install core and protection with worldedit, it will crash when you use wand tools right click to choose position.
Below is debug.log and crash report
[debug.log](https://github.com/ProjectEssentials/ProjectEssentials-Core/files/4736576/debug.log)
[crash-2020-06-05_21.42.24-client.txt](https://github.com/ProjectEssentials/ProjectEssentials-Core/files/4736578/crash-2020-06-05_21.42.24-client.txt)

**Comment by MairwunNx** [comment]
You was in single player or join to server with mods?

**Comment by MairwunNx** [comment]
Client loads configurations correctly. I'll try reproduce this by connecting on server with mods.

**Comment by MairwunNx** [comment]
Can't reproduce this bug with 1.14.4, you can reproduce this?

**Comment by KuroNoSeiHai** [comment]
I join to server with mods, client crashed but server is not.

**Comment by MairwunNx** [comment]
Hm, if you can, try reproduce this again. I'll test this on 1.15.2 later

Thank you for testing!

**Comment by KuroNoSeiHai** [comment]
Fixed. And I updated translation.

**Comment by MairwunNx** [comment]
If this issue not actual for you, you can close this =), thanks.

**Comment by MairwunNx** [comment]
Please, open this if that issue will reproduces, thank you!
